[program:mariadb]
command=/usr/sbin/mariadbd --user=mysql --datadir=/app/data/mysql --socket=/var/run/mysqld/mysqld.sock --bind-address=127.0.0.1 --port=3306
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/mariadb.out.log
stderr_logfile=/var/log/supervisor/mariadb.err.log
priority=10

[program:redis]
command=/usr/bin/redis-server --port 6379 --bind 127.0.0.1 --dir /app/data/redis --daemonize no --save 60 1 --appendonly yes
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/redis.out.log
stderr_logfile=/var/log/supervisor/redis.err.log
priority=10
